### ISSUE TITLE
Use --network to specify what network to use

### ISSUE THREAD

**Issue by MikeFair** [tolitius/stellar-mc#1]
Allow `bb8 --network namedNetwork` to switch between networks.
Allow `bb8 --horizon serverAlias_or_serverURL` to specify which horizon server URL to use.

`namedNetwork` would refer to a file that had something like:
```{
  "networkName":"Friendly Official Name of the Network",
  "networkPassphrase":"The Passphrase of the Network",
  "defaultHorizon":"shortName",
  "horizonEntries":[
    {"name":"shortName", "url":"https://my-horizon.domain.dom/"},
    {"name":"otherName", "url":"https://otherdomain.tld/horizon/"},
    {"name":"oneMore", "url":"https://horizon-backup.domain.dom"}
  ]
}```

**Comment by tolitius** [comment]
I think if the `--network` is not provided it should use testnet by default which could still be overwritten with `STELLAR_NETWORK` env.

I like the idea, but I think the format could be better:

```json
{
   "network":{
      "name":"Friendly Official Name of the Network",
      "passphrase":"The Passphrase of the Network"
   },
   "horizon":{
      "entries":[
         {
            "name":"shortName",
            "url":"https://my-horizon.domain.dom/"
         },
         {
            "name":"otherName",
            "url":"https://otherdomain.tld/horizon/"
         },
         {
            "name":"oneMore",
            "url":"https://horizon-backup.domain.dom"
         }
      ],
      "default":"shortName"
   }
}
```

I also would not want to overload a single `--horizon` flag with both "alias" and "url". We could probably do:

```
--horizon alias
--horizon-url url
```

**Comment by MikeFair** [comment]
Well done on both counts!
Agreed, the format I put out was definitely intended as more "inspirational" than "well thought out" ;)
and the `--horizon-url` split off is brilliant!

I especially like that the "horizon" section is easily mimicked to make a "stellar-core" section.

If "horizon" was brought inside the "network" object, then that object fully describes the "network".

What do you think of:
```
{
  "mystellar-public": {
    "name":"Friendly Official Name of the Network",
    "passphrase":"The Passphrase of the Network",
    "horizon": {
      "entries": {
        "shortName":{"url":"https://my-horizon.domain.dom/"},
        "otherName":{"url":"https://otherdomain.tld/horizon/"},
        "oneMore":{"url":"https://horizon-backup.domain.dom"}
      },
      "default":"shortName"
    }
  },
  "mystellar-testNet": {
    "name":"Friendly Official Name of the Test Network",
    "passphrase":"The Passphrase of the Test Network",
    "horizon": {
      "entries": {
        "shortName":{"url":"https://my-horizon-testnet.domain.dom/"},
        "otherName":{"url":"https://otherdomain.tld/horizon-testnet/"},
        "oneMore":{"url":"https://horizon-backup-testnet.domain.dom"}
      },
      "default":"shortName"
    }
  }
}
```
Obviously feel free to change/rearrange as you see fit and fits your preferred style.

**Comment by tolitius** [comment]
in order for BB-8 to find this network file we might need to introduce a `BB8_HOME` where this and other config files will live. In addition/or alternatively there can be `STELLAR_NETWORK_CONFIG` that would point directly to this file.

**Comment by MikeFair** [comment]
I don't think anyone would have a problem with ~/.stellar/bb8
You might even be able to do something like ~/.stellar/keys

**Comment by MikeFair** [comment]
Oh duh; when I was thinking of it, I was thinking you'd have to provide the
filename as a parameter; perhaps --config
I don't know if Go has a library to manage the "user folder" files across
various platforms; a simple command line config option would be enough to
get things started

**Comment by tolitius** [comment]
right, needs to be supported across OSs, hence I thought of `BB8_HOME`.

starting from Go 1.9, this would cross compile (since it does not longer use `cgo`):

```go
cuser, err := user.Current()
if err != nil {
    return "", err
}
return cuser.HomeDir, nil
```

**Comment by tolitius** [comment]
will prefix it with `network`, so there is room for other non network related config options:

```json
{"network":{
  "mystellar-public":{
    "name":"Friendly Official Name of the Network",
    "passphrase":"The Passphrase of the Network",
    "horizon":{
      "entries":{
        "shortName":{
          "url":"https://my-horizon.domain.dom/"
        },
        "otherName":{
          "url":"https://otherdomain.tld/horizon/"
        },
        "oneMore":{
          "url":"https://horizon-backup.domain.dom"
        }
      },
      "default":"shortName"
    }
  },
  "mystellar-testNet":{
    "name":"Friendly Official Name of the Test Network",
    "passphrase":"The Passphrase of the Test Network",
    "horizon":{
      "entries":{
        "shortName":{
          "url":"https://my-horizon-testnet.domain.dom/"
        },
        "otherName":{
          "url":"https://otherdomain.tld/horizon-testnet/"
        },
        "oneMore":{
          "url":"https://horizon-backup-testnet.domain.dom"
        }
      },
      "default":"shortName"
    }
  }
}
}
```

**Comment by MikeFair** [comment]
Nice; does that make it "networks" (plural)?
Otherwise it looks great!

**Comment by tolitius** [comment]
initial pass for this feature is in. a sample config is in `examples/` can you give it a go?

```
Flags:
  -h, --help                 help for bb
      --horizon string       horizon server name from the BB8 config file. by default BB8 would look in "home.dir/.bb8/bb8.json" file
      --horizon-url string   horizon server URL to use for "this" transaction
  -n, --network string       network name from the BB8 config file. by default BB8 would look in "home.dir/.bb8/bb8.json" file
```

`network` is singular since it is hierarchical: i.e. "network -> mystellar-testNet -> ..."

**Comment by MikeFair** [comment]
Well alright alright!

I didn't do any extensive testing but I did test using a network name with
-n [netname] with a couple different default server aliases and -n
[netname] --horizon [alias] on both Windows and Ubuntu and they worked
exactly as expected.  On Windows the config file is
"\Users\[UserName]\.bb8\bb8.json".

**Comment by tolitius** [comment]
great, thanks. I don't have any custom horizon servers to point to to test so this is very helpful.

**Comment by tolitius** [comment]
docs are added. this feature is in `0.1.11` release
